name: Dependabot Summarize Comment
description: Dependabotのプルリクの要約コメント作成
inputs:
  openai_api_key:
    description: OpenAIのAPIキー
    required: true
  github_token:
    description: GitHubのトークン
    required: true

branding:
  icon: award
  color: orange

runs:
  using: composite
  steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Summarize pull requests
      run: deno run --allow-net --allow-env $GITHUB_ACTION_PATH/main.ts
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
